version: "2"
sql:
  - engine: "postgresql"
    schema: "postgre/audit/schema"
    queries: "postgre/audit/queries"
    gen:
      go:
        package: "queriesgen"
        out: "postgre/audit/queriesgen"