version: "2"
sql:
  - engine: "postgresql"
    schema: "postgre/audit/schema"
    queries: "postgre/audit/queries"
    gen:
      go:
        package: "sqlcgen"
        out: "postgre/audit/sqlcgen"
        sql_package: "pgx/v5"