// Package example provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package example

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	// Body Free-form contents.
	Body *string `json:"body,omitempty"`

	// Title Short label for the note.
	Title string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	// Message What went wrong.
	Message string `json:"message"`
}

// GetExampleVisitsResponse defines model for GetExampleVisitsResponse.
type GetExampleVisitsResponse struct {
	// Visits Number of times this endpoint has been called.
	Visits int64 `json:"visits"`
}

// Note defines model for Note.
type Note struct {
	// Body Free-form contents.
	Body string `json:"body"`

	// CreatedAt When the note was stored.
	CreatedAt time.Time `json:"created_at"`

	// Id Generated identifier.
	Id int64 `json:"id"`

	// Title Short label for the note.
	Title string `json:"title"`
}

// ListExampleNotesParams defines parameters for ListExampleNotes.
type ListExampleNotesParams struct {
	// Limit Maximum number of notes to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateExampleNoteJSONRequestBody defines body for CreateExampleNote for application/json ContentType.
type CreateExampleNoteJSONRequestBody = CreateNoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List example notes
	// (GET /example/notes)
	ListExampleNotes(c *gin.Context, params ListExampleNotesParams)
	// Create an example note
	// (POST /example/notes)
	CreateExampleNote(c *gin.Context)
	// Get example visits
	// (GET /example/visits)
	GetExampleVisits(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListExampleNotes operation middleware
func (siw *ServerInterfaceWrapper) ListExampleNotes(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExampleNotesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListExampleNotes(c, params)
}

// CreateExampleNote operation middleware
func (siw *ServerInterfaceWrapper) CreateExampleNote(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateExampleNote(c)
}

// GetExampleVisits operation middleware
func (siw *ServerInterfaceWrapper) GetExampleVisits(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetExampleVisits(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/example/notes", wrapper.ListExampleNotes)
	router.POST(options.BaseURL+"/example/notes", wrapper.CreateExampleNote)
	router.GET(options.BaseURL+"/example/visits", wrapper.GetExampleVisits)
}

type ListExampleNotesRequestObject struct {
	Params ListExampleNotesParams
}

type ListExampleNotesResponseObject interface {
	VisitListExampleNotesResponse(w http.ResponseWriter) error
}

type ListExampleNotes200JSONResponse []Note

func (response ListExampleNotes200JSONResponse) VisitListExampleNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListExampleNotes400JSONResponse Error

func (response ListExampleNotes400JSONResponse) VisitListExampleNotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExampleNoteRequestObject struct {
	Body *CreateExampleNoteJSONRequestBody
}

type CreateExampleNoteResponseObject interface {
	VisitCreateExampleNoteResponse(w http.ResponseWriter) error
}

type CreateExampleNote201JSONResponse Note

func (response CreateExampleNote201JSONResponse) VisitCreateExampleNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExampleNote400JSONResponse Error

func (response CreateExampleNote400JSONResponse) VisitCreateExampleNoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetExampleVisitsRequestObject struct {
}

type GetExampleVisitsResponseObject interface {
	VisitGetExampleVisitsResponse(w http.ResponseWriter) error
}

type GetExampleVisits200JSONResponse GetExampleVisitsResponse

func (response GetExampleVisits200JSONResponse) VisitGetExampleVisitsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List example notes
	// (GET /example/notes)
	ListExampleNotes(ctx context.Context, request ListExampleNotesRequestObject) (ListExampleNotesResponseObject, error)
	// Create an example note
	// (POST /example/notes)
	CreateExampleNote(ctx context.Context, request CreateExampleNoteRequestObject) (CreateExampleNoteResponseObject, error)
	// Get example visits
	// (GET /example/visits)
	GetExampleVisits(ctx context.Context, request GetExampleVisitsRequestObject) (GetExampleVisitsResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListExampleNotes operation middleware
func (sh *strictHandler) ListExampleNotes(ctx *gin.Context, params ListExampleNotesParams) {
	var request ListExampleNotesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListExampleNotes(ctx, request.(ListExampleNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListExampleNotes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListExampleNotesResponseObject); ok {
		if err := validResponse.VisitListExampleNotesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateExampleNote operation middleware
func (sh *strictHandler) CreateExampleNote(ctx *gin.Context) {
	var request CreateExampleNoteRequestObject

	var body CreateExampleNoteJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateExampleNote(ctx, request.(CreateExampleNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateExampleNote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateExampleNoteResponseObject); ok {
		if err := validResponse.VisitCreateExampleNoteResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExampleVisits operation middleware
func (sh *strictHandler) GetExampleVisits(ctx *gin.Context) {
	var request GetExampleVisitsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetExampleVisits(ctx, request.(GetExampleVisitsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExampleVisits")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetExampleVisitsResponseObject); ok {
		if err := validResponse.VisitGetExampleVisitsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
