application:
  name:
  version:
  environment:

server:
  mode:  # test, debug, or release
  port:
  timeout:

databases:
  postgre:
    analytics:
      host:
      port:
      username:
      password:
      name:
    audit:
      host:
      port:
      username:
      password:
      name:

logger:
  format:  # json or console 
  level:   # debug, info, warn, or error
  output:  # stdout, stderr or a file path