openapi: "2.0.0"
info:
  version: 2.0.0
  title: Health
paths:
  /health:
    get:
      responses:
        '200':
          description: successfully get health
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
components:
  schemas:
    Health:
      type: object
      required:
        - condition
      properties:
        condition:
          type: string
          example: OK