openapi: "3.0.0"
info:
  version: 1.0.0
  title: Health API
paths:
  /health:
    get:
      responses:
        '200':
          description: Successfully retrieved health
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHealthResponse'
components:
  schemas:
    GetHealthResponse:
      type: object
      required:
        - condition
      properties:
        condition:
          type: string
          example: "Healthy"